version: 2.1

jobs:
  build-branches-amd64:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Podman
          command: |
            . /etc/os-release
            echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
            curl -L "http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key" | sudo apt-key add -
            sudo apt-get update -qq
            sudo apt-get -qq -y install podman
      - run:
          name: Build AMD64 Container Image
          command: |
            cp loadbalancer-playbook/version/keepalived/Dockerfile.amd64 loadbalancer-playbook/version/keepalived/Dockerfile
            bash init.sh
            sudo podman system prune --all --force
            sudo podman build -t huangqw/playbook:amd64-$CIRCLE_BRANCH .
            echo $DOCKER_PASSWORD | sudo podman login -u $DOCKER_USERNAME --password-stdin docker.io
            sudo podman push huangqw/playbook:amd64-$CIRCLE_BRANCH

  build-tags-amd64:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Podman
          command: |
            . /etc/os-release
            echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
            curl -L "http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key" | sudo apt-key add -
            sudo apt-get update -qq
            sudo apt-get -qq -y install podman
      - run:
          name: Build AMD64 Container Image
          command: |
            cp loadbalancer-playbook/version/keepalived/Dockerfile.amd64 loadbalancer-playbook/version/keepalived/Dockerfile
            bash init.sh
            sudo podman system prune --all --force
            sudo podman build -t huangqw/playbook:amd64-$CIRCLE_TAG .
            echo $DOCKER_PASSWORD | sudo podman login -u $DOCKER_USERNAME --password-stdin docker.io
            sudo podman push huangqw/playbook:amd64-$CIRCLE_TAG

workflows:
  version: 2
  build-for-branches:
    jobs:
      - build-branches-amd64
  build-for-tags:
    jobs:
      - build-tags-amd64:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/



