version: 2.1

jobs:
  build-branches-amd64:
    machine:
      image: ubuntu-2004:2024.01.1
    steps:
      - checkout
      - run:
          name: Install Podman Dependencies
          command: |
            sudo apt-get update
            sudo apt-get -y install software-properties-common uidmap
            sudo add-apt-repository -y ppa:kubic/libcontainers
            sudo apt-get update
            sudo apt-get -y install podman fuse-overlayfs slirp4netns
      - run:
          name: Configure Podman
          command: |
            sudo mkdir -p /etc/containers/registries.conf.d
            sudo mkdir -p /var/lib/containers/storage
            
            cat \<< EOF | sudo tee /etc/containers/registries.conf.d/docker.conf
            unqualified-search-registries = ["docker.io"]
            EOF

            cat \<< EOF | sudo tee /etc/containers/containers.conf
            [engine]
            cgroup_manager = "cgroupfs"
            events_logger = "file"
            EOF

            cat \<< EOF | sudo tee /etc/containers/storage.conf
            [storage]
            driver = "vfs"
            graphroot = "/var/lib/containers/storage"
            runroot = "/run/containers/storage"
            EOF
      - run:
          name: Build AMD64 Container Image
          command: |
            cp loadbalancer-playbook/version/keepalived/Dockerfile.amd64 loadbalancer-playbook/version/keepalived/Dockerfile
            bash init.sh
            sudo podman system prune --all --force
            sudo podman build -t huangqw/playbook:amd64-$CIRCLE_BRANCH .
            echo $DOCKER_PASSWORD | sudo podman login -u $DOCKER_USERNAME --password-stdin docker.io
            sudo podman push huangqw/playbook:amd64-$CIRCLE_BRANCH

  build-tags-amd64:
    machine:
      image: ubuntu-2004:2024.01.1
    steps:
      - checkout
      - run:
          name: Install Podman Dependencies
          command: |
            sudo apt-get update
            sudo apt-get -y install software-properties-common uidmap
            sudo add-apt-repository -y ppa:kubic/libcontainers
            sudo apt-get update
            sudo apt-get -y install podman fuse-overlayfs slirp4netns
      - run:
          name: Configure Podman
          command: |
            sudo mkdir -p /etc/containers/registries.conf.d
            sudo mkdir -p /var/lib/containers/storage
            
            cat \<< EOF | sudo tee /etc/containers/registries.conf.d/docker.conf
            unqualified-search-registries = ["docker.io"]
            EOF

            cat \<< EOF | sudo tee /etc/containers/containers.conf
            [engine]
            cgroup_manager = "cgroupfs"
            events_logger = "file"
            EOF

            cat \<< EOF | sudo tee /etc/containers/storage.conf
            [storage]
            driver = "vfs"
            graphroot = "/var/lib/containers/storage"
            runroot = "/run/containers/storage"
            EOF
      - run:
          name: Build AMD64 Container Image
          command: |
            cp loadbalancer-playbook/version/keepalived/Dockerfile.amd64 loadbalancer-playbook/version/keepalived/Dockerfile
            bash init.sh
            sudo podman system prune --all --force
            sudo podman build -t huangqw/playbook:amd64-$CIRCLE_TAG .
            echo $DOCKER_PASSWORD | sudo podman login -u $DOCKER_USERNAME --password-stdin docker.io
            sudo podman push huangqw/playbook:amd64-$CIRCLE_TAG

workflows:
  version: 2
  build-for-branches:
    jobs:
      - build-branches-amd64
  build-for-tags:
    jobs:
      - build-tags-amd64:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/



