version: 2.1

jobs:
  build-branches-amd64:
    machine:
      image: ubuntu-2004:2024.01.1
    steps:
      - checkout
      - run:
          name: Install Podman
          command: |
            sudo apt-get update
            sudo apt-get install -y curl gnupg2
            . /etc/os-release
            echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-backports main" | sudo tee /etc/apt/sources.list.d/backports.list
            sudo apt-get update
            sudo apt-get install -y -t ${VERSION_CODENAME}-backports podman uidmap slirp4netns
      - run:
          name: Configure Podman
          command: |
            sudo mkdir -p /etc/containers
            echo "unqualified-search-registries = ['docker.io']" | sudo tee /etc/containers/registries.conf
            echo '[storage]
            driver = "vfs"
            runroot = "/run/containers/storage"
            graphroot = "/var/lib/containers/storage"' | sudo tee /etc/containers/storage.conf
      - run:
          name: Build AMD64 Container Image
          command: |
            cp loadbalancer-playbook/version/keepalived/Dockerfile.amd64 loadbalancer-playbook/version/keepalived/Dockerfile
            bash init.sh
            sudo podman system prune --all --force
            sudo podman build -t huangqw/playbook:amd64-$CIRCLE_BRANCH .
            echo $DOCKER_PASSWORD | sudo podman login -u $DOCKER_USERNAME --password-stdin docker.io
            sudo podman push huangqw/playbook:amd64-$CIRCLE_BRANCH

  build-tags-amd64:
    machine:
      image: ubuntu-2004:2024.01.1
    steps:
      - checkout
      - run:
          name: Install Podman
          command: |
            sudo apt-get update
            sudo apt-get install -y curl gnupg2
            . /etc/os-release
            echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-backports main" | sudo tee /etc/apt/sources.list.d/backports.list
            sudo apt-get update
            sudo apt-get install -y -t ${VERSION_CODENAME}-backports podman uidmap slirp4netns
      - run:
          name: Configure Podman
          command: |
            sudo mkdir -p /etc/containers
            echo "unqualified-search-registries = ['docker.io']" | sudo tee /etc/containers/registries.conf
            echo '[storage]
            driver = "vfs"
            runroot = "/run/containers/storage"
            graphroot = "/var/lib/containers/storage"' | sudo tee /etc/containers/storage.conf
      - run:
          name: Build AMD64 Container Image
          command: |
            cp loadbalancer-playbook/version/keepalived/Dockerfile.amd64 loadbalancer-playbook/version/keepalived/Dockerfile
            bash init.sh
            sudo podman system prune --all --force
            sudo podman build -t huangqw/playbook:amd64-$CIRCLE_TAG .
            echo $DOCKER_PASSWORD | sudo podman login -u $DOCKER_USERNAME --password-stdin docker.io
            sudo podman push huangqw/playbook:amd64-$CIRCLE_TAG

workflows:
  version: 2
  build-for-branches:
    jobs:
      - build-branches-amd64
  build-for-tags:
    jobs:
      - build-tags-amd64:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/



